base_url = "https://jesse.cafe"
author = "Jesse Falzone"
compile_sass = true
build_search_index = false
minify_html = true
generate_feed = true
ignored_content = ["*.{jpg,jpeg,png,gif}"]
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
site_name = "jesse.cafe"
