base_url = "https://jesse.cafe"
compile_sass = true
build_search_index = false
minify_html = true
generate_feed = true
taxonomies = [
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
author = "Jesse Falzone"
site_name = "jesse.cafe"
